FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYSPARK_PYTHON=python3 \
    JAVA_HOME=/usr/lib/jvm/default-java

RUN apt-get update \
    && apt-get install -y --no-install-recommends default-jre-headless procps curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline/ ./pipeline/

CMD ["python", "pipeline/run_pipeline.py"]
